[package]
name = "ant_sim"
version = "0.1.0"
authors = ["asdf <asdf>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
piston = "0.53.0"
piston2d-graphics = "0.40.0"
piston2d-opengl_graphics = "0.78.0"
pistoncore-glutin_window = "0.69.0"
ndarray = "0.15.1"
ndarray-linalg = "0.13.1"
nalgebra = "0.26.2"
nalgebra-glm = "0.12.0"
rayon = "1.5.0"
